Lab5
LuckyHorseshoe-chan/IU5-Frontend-2021 pull request #5
Opened 2021-03-28 14:05 UTC by LuckyHorseshoe-chan

2021-03-30 18:34 UTC, youraavdeev requested changes

2021-03-30 18:34 UTC, youraavdeev commented on lab5/1.js
> + Object.defineProperty(Array.prototype, 'myMap', {
можно добавить полифил по-другому - проще

2021-03-30 18:34 UTC, youraavdeev commented on lab5/2.js
> +function add(a, b, c) {
а зачем тут это

2021-03-30 18:34 UTC, youraavdeev commented on lab5/3.js
> +    return f.bind(context);
ты же понимаешь что суть в том чтобы без использования bind написать свой bind

2021-03-30 18:34 UTC, youraavdeev commented on lab5/4.js
> +        console.log(obj.result)
ненужные консоль логи

2021-03-31 15:04 UTC, LuckyHorseshoe-chan commented on lab5/4.js
> +        console.log(obj.result)
Пофиксила всё

2021-04-01 17:15 UTC, youraavdeev commented
ок вливай

2021-04-01 17:17 UTC, merged